server:
  port: 8088
spring:
  application:
    name: blog-app
  datasource:
    password: admin@123
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=blogdb
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

